namespace TornCityAPISharp.UserStats
{
    public enum UserMethods
    {
        networth,
        bazaar,
        display,
        inventory,
        hof,
        travel,
        events,
        messages,
        education,
        medals,
        honors,
        notifications,
        personalstats,
        workstats,
        crimes,
        icons,
        cooldowns,
        money,
        perks,
        battlestats,
        bars,
        profile,
        basic,
        attacks,
        attacksfull,
        stocks,
        properties,
        jobpoints,
        merits
    }
}
